version: "3.8"

services:
  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    expose:
      - '5432'
 
  pgadmin:
    image: adminer
    restart: always
    links:
      - database
    ports:
      - 8080:8080